FROM ubuntu:latest
FROM python:3.7
MAINTAINER kondin@etown.ru

COPY . .

RUN pip3 install -r requirements.txt

#Install Cron
RUN apt-get update
RUN apt-get -y install cron
RUN apt-get -y install less
RUN apt-get -y install vim

